/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// NOTE: This file should not be edited.
// It is auto-generated by Next.js, but we keep it committed for TS setup.

